stages:
  - install
  - build
  - test
  - deploy

install:
  stage: install
  script:
    - node -v
    - npm -v
    - npm install

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - echo "Skipping tests"

deploy:
  stage: deploy
  script:
    - echo "Déploiement..."
